### PR TITLE
combined vegatooltip

### PR DESCRIPTION
**Pull request by lujiacn**
combined the vega-tooltip repo from: https://github.com/vega/vega-tooltip

### CODE REVIEW

**Comment by hrbrmstr** [comment]
many thanks! If you could add yourself as a contributor to the `DESCRIPTION` file (this is a pretty major enhancement IMO) that'd be great for the community to know who provided the feature (and to ensure you get the proper credit)

**Comment by timelyportfolio** [comment]
this is great @lujiacn.  Hard to keep up, and `vegalite` will require substantial rewrite for https://github.com/vega/vega-lite/tree/vg3.

**Comment by hrbrmstr** [comment]
O_o

Hard to keep up, indeed! :-)

**Comment by lujiacn** [comment]
Hi @hrbrmstr, thanks for created the wonderful R package. Just updated description, hope the format is correct. 
@timelyportfolio yes, Hard to keep up.  I modified ggvis to use vega2, now vega3 is comming -_-!

**Pull request merged**
