### PR TITLE
Update to vega-lite 2.0

### PR DESCRIPTION
**Pull request by AliciaSchep**
Initial PR for update to Vega-Lite 2.0, per #28 . Probably not quite ready yet, but figured I'd get the PR in to start review & discussion

Changes are enumerated in NEWs and include:

* Update of JS libraries
* Updates spec.js and vegalite.js to match new api for vega-embed and vega-tooltip.
* Add z-schema javascript library and a function validate_vl that checks whether schema is valid vega-lite2. Updates tests to use validate_vl.
* Update of viewport sizing handling.  Vegalite no longer has viewport_width arguments so this now goes to htmlwidgets.  Some CSS was also added in order to best replicate the old behavior, where scrolling was enabled when viewport too small to fit full plot.
* Updates to to_spec and embed_spec to give valid spec for vega-lite2
* Deprecate axis_facet_row and axis_facet_col because behaviour currently un-supported by vega-lite 2.
* Update to axis_vl function so that arguments match those supported by vega-lite 2 axis config.
* band_size argument now named range_step, to match vega-lite 2 naming
* cell_size and cell_config deprecated in favor of view_size and view_config to better match new naming of field in vega-lite 2
* grid_facet deprecated because there is no longer a facet field in config in vega-lite 2
* Bug fixes to capture_widget [not really related to V2, but caught when trying to make sure it still worked]

I tested:
* Passed R CMD check on my computer (Ubuntu 16.04, R 3.4.2)
* Vignette gives reasonable output.  Main difference with old version is a few unsupported features by vega-lite 2, and seemingly different color defaults
* Vignette, examples, & test give valid vega-lite 2 specs

I have not tested:
* All arguments to all functions will result in valid vegalite 2 spec
* Passes tests on other OS, r versions, etc

I know that there are some issues with the config_* functions and arguments.  Given that the config schema seems to have been overhauled a fair bit in vega-lite 2, I think some new functions and possibly re-grouping of existing functionality there might be warranted.  I started some work along these lines in another branch, but also got kind of carried away with some helper functions so I think it may make sense for that to be a separate PR.  One issue I noticed is that there is inconsistency in the package with argument naming -- some functions use snake_case instead of vega-lite's preferred camelCase, while others use the camelCase. I think it would be nice for that to be standardized for all arguments that are tied directly to vega-lite  properties.

With regards to validating the JSON, I tried jsonvalidate as suggested by #26.  I could not get it to work on test examples with this schema.  I thus brought in the z-schema js library, which I noticed the vega-lite repository using.  That library works well.  If bringing in another js library is unacceptable, I can look into other options

### CODE REVIEW

**Comment by jsonbecker** [comment]
Awesome. Will review more thoroughly sometime in the next couple of days. One thought (and I’m on my phone so you may already do this): if we’re adding a new js library mostly for testing, it’d be best if we can include it in the tests directory so that CRAN installers/folks not using —install-tests flag don’t get stuck with it.

**Comment by AliciaSchep** [comment]
Great! I included z-schema JS library in inst/htmlwidgets/lib along with the others, which is probably not the right place for it! Although used mostly for testing, there is also a function in package itself called `validate_vl`. That function and library could get moved to tests, as you suggest.  However, one nice feature of z-schema is that you can validate sub-schemas, so it could be nice in future to have each function have validation for just the stuff that gets added to the spec -- if arguments don't create valid spec, you would get a warning (otherwise you are likely to get silent ignoring of issues).

**Comment by AliciaSchep** [comment]
@jsonbecker did you get a chance to look at this?    I'm happy to follow up on any suggestions or things that need improvement in current PR...

Regarding the extra zchema library, I just pushed an update to remove the zschema lib and use jsonvalidate package (available on CRAN) instead. I had tried it before unsuccessfully, but tried again and am not sure what was different but it actually seems to work well as far as I can tell.

**Comment by jsonbecker** [comment]
I looked but not closely enough. I promise a review up by Monday.

http://www.jsonbecker.com/contact/

**Comment by AliciaSchep** [comment]
Great, thanks! :+1:

**Comment by AliciaSchep** [comment]
hi @jonloyens it might be worth checking out https://github.com/ijlyttle/altair 

That is a new (still in development but already working fairly well, with more functionality than this fork) package that wraps python's altair interface to vegalite.  While porting a python port of a javascript package may seem a bit round-a-bout, it has some major advantages in that porting a python package is much easier than designing & maintaining an R api for a json specification.  The altair python developers have already put in a lot of time & effort into making a good api for vegalite, and the altair r package seeks to take advantage of all that work. The current api for that package is not as congruous with the 'tidyverse' style, but eventually there may be a pipable api (see https://github.com/ijlyttle/altair/issues/15).

**Comment by jonloyens** [comment]
Thanks for the tip @AliciaSchep - I will give that one a try as well (although it does seem like many level of indirection, I get it)

**Pull request merged**
